### ISSUE TITLE
update env vars

### ISSUE THREAD

**Issue by elrayle** [cul-it/qa_server_aws_deploy#3]
New customization vars were added to the image.  They need to be set for our app.  The new env vars and our values for them are...

```
## --------------------
## QA_SERVER CUSTOMIZATIONS
## --------------------
PREFERRED_TIME_ZONE_NAME=Eastern Time (US & Canada)
DISPLAY_HISTORICAL_DATA=true
HISTORICAL_DATA_DEFAULT_TIME_PERIOD=:month
DISPLAY_PERFORMANCE_GRAPH=true
DISPLAY_PERFORMANCE_DATATABLE=false
PERFORMANCE_DATA_DEFAULT_TIME_PERIOD=:month
SUPPRESS_PERFORMANCE_LOGGING=false
MONITOR_STATUS_LOGGING_ENABLED=true

## --------------------
## QA CUSTOMIZATIONS
## --------------------
ENABLE_CORS_HEADERS=true
DEFAULT_LANGUAGE=:en
SUPPRESS_IP_DATA_FROM_LOG=false
```

**Comment by gdelisle** [comment]
I agree that there's no reason why we can't include these with the public version of the app, since they're not secrets. They also all have defaults so there's no reason we must include them. Maybe we can supply the .env.example file with these variables filled in?

**Comment by elrayle** [comment]
In LD4P/qa_server_aws_deploy, the .env.example file does have these new env vars with example values.  This issue is for determining how to set these vars for cult-it/qa_server_aws_deploy.

**Comment by elrayle** [comment]
For now, I manually update the -int .env file in the S3 bucket.

Questions:
* do they get copied to the root of the application or are they picked up directly from S3?
* will these automatically be picked up?
* if not auto-picked up, what is the process? (e.g. manually run the -int deploy GH action, restart the server for the application, ???)

**Comment by elrayle** [comment]
Manual deploy for -stg and -prod are pending creation of S3 buckets with new consistent naming.  

* Issue #11

**Comment by elrayle** [comment]
- [x] cloud formation stacks are consistent
- [x] S3 buckets use consistent
- [x] github actions are consistent
- [x] ECS clusters are consistent
